---
title: "Week3-3 Creating New"
author: "Kidult"
date: "2019/1/30"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r input, echo=FALSE}
#inputPanel( # in grey box
#selectInput("n_breaks", label = "Number of bins:",choices = c(10, 20, 35, 50), selected = 20),
#sliderInput("bw_adjust", label = "Bandwidth adjustment:",min = 0.2, max = 2, value = 1, step = 0.2)
           #)
#flowLayout(numericInput("rows", "How many rows?", 5),selectInput("letter", "Which letter?", LETTERS),sliderInput("value", "What value?", 0, 100, 50))

fileUrl <- "https://data.baltimorecity.gov/api/views/k5ry-ef3g/rows.csv?accessType=DOWNLOAD"
download.file(fileUrl,destfile="restaurants.csv")
restData <- read.csv("restaurants.csv")

fluidPage(
  column(4,
         br("An restaurant's CSV File Link HERE:"),
         verticalLayout(a(href=fileUrl, "restaurants.csv")),
         br("head() table:"),
         renderTable(table(restData$neighborhood))
         )
  )

```