---
title: "Week4-2 Regular Exp"
author: "Kidult"
date: "2019/2/11"
output: html_document
runtime: shiny
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r input, echo=FALSE}
#inputPanel( # in grey box
#selectInput("n_breaks", label = "Number of bins:",choices = c(10, 20, 35, 50), selected = 20),
#sliderInput("bw_adjust", label = "Bandwidth adjustment:",min = 0.2, max = 2, value = 1, step = 0.2)
           #)
#flowLayout(numericInput("rows", "How many rows?", 5),selectInput("letter", "Which letter?", LETTERS),sliderInput("value", "What value?", 0, 100, 50))

# ^ begin
# $ end
# [AB] [Aa] OR
# [a-z] [a-zA-Z] [0-9]
# [^?.]$ NOT ?/. END

# x.y "." ANY char
# xxx|yyy OR words
# XXX|YYY|ZZZ|xxx|yyy|zzz

# ^[Gg]ood|[Bb]ad   == Start with Good/good OR have Bad/bad 
# ^([Gg]ood|[Bb]ad) ==  Start with Good/good/Bad/bad

# [Gg]eorge( [Ww]\.)? [Bb]ush  == George/george Bush/bush OR George/george W./w. Bush/bush
##               \. means char "." NOT ANY Char
##                  ? Exist or NOT Exist

# (.*) ANY Char rep ANY Times, including Zero Time
# [0-9]+(.*)[0-9]+ == 72 2 342 1284 12984729 ... Find Nums ~
# [Bb]ush( +[^ ]+ +){1,5} debate
# begin with Bush/bush
# end with debate
# 1~5 words display between Bush/bush..and..debate
# ( +[^ ]+ +) space nospaceChar space
# Bush/bush(space)(nospaceChar)(space)debate
# Like
# Bush and debate
# " and " == (space)(nospaceChar)(space) == ( +[^ ]+ +) 1 Time
# {m,n} m~n Times

# \
# +([a-zA-Z]+) +\1 +

# * greedy 
# ^s(.*)s Start with "s", end with "s", * between ^s and s$
# ^s(.*)s$

# grep/grepl/sub/gsub

#fluidPage(
#  column(4,
#         br("An restaurant's CSV File Link HERE:"),
#         verticalLayout(a(href=fileUrl, "restaurants.csv")),
#         br("head() table:"),
#         renderTable(table(restData$neighborhood))
#         )
#  )
```